name: Build CLI Binaries (Test)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-cli-binaries-test.yml'
      - 'openhands-cli.spec'
      - 'openhands/cli/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install minimal dependencies
      run: |
        # Create a minimal pyproject.toml for testing
        poetry init --no-interaction --name openhands-cli-test --python "^3.11"
        poetry add pyinstaller
        
        # Install core OpenHands dependencies manually
        pip install aiohttp litellm docker pydantic toml rich prompt_toolkit
    
    - name: Test PyInstaller build
      run: |
        # Simple test build
        pyinstaller \
          --name openhands-test \
          --onefile \
          --clean \
          --noconfirm \
          --hidden-import openhands \
          openhands/cli/main.py
        
        # Check if binary was created
        ls -la dist/
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-binary
        path: dist/openhands-test