name: Build CLI Binaries All Platforms (Docker)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        type: string
        default: 'manual'
      create_release:
        description: 'Create a release'
        required: false
        type: boolean
        default: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Linux binary in Docker
      run: |
        # Linuxバイナリのビルド
        docker build -f Dockerfile.cli-build -t openhands-linux-builder .
        docker run --rm -v "$(pwd)/dist-linux:/output" openhands-linux-builder
        ls -la dist-linux/
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: openhands-linux-x86_64
        path: dist-linux/*

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Windows placeholder
      run: |
        # Windows cross-compilation is complex, create a placeholder with instructions
        mkdir -p dist-windows
        cat > dist-windows/README-Windows.txt <<'EOF'
        Windows Binary Build Instructions
        =================================
        
        Windows binaries cannot be easily cross-compiled from Linux using Docker.
        
        To build the Windows binary:
        
        1. Use a Windows machine or VM
        2. Install Python 3.12
        3. Install Poetry: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python
        4. Clone the repository
        5. Run: poetry install
        6. Run: poetry run pip install pyinstaller
        7. Run: poetry run pyinstaller openhands-cli.spec --clean --noconfirm
        8. The binary will be in dist/openhands.exe
        
        Alternatively, use the native GitHub Actions workflow (build-cli-binaries.yml)
        which builds on actual Windows runners.
        EOF
        
        cd dist-windows && zip openhands-windows-x86_64.zip README-Windows.txt
    
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: openhands-windows-x86_64
        path: dist-windows/*

  build-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create macOS cross-compile Dockerfile
      run: |
        cat > Dockerfile.macos-cross <<'EOF'
        FROM python:3.12-slim
        
        # Install basic tools
        RUN apt-get update && \
            apt-get install -y \
                gcc \
                g++ \
                make \
                curl \
                git \
                zip \
                && rm -rf /var/lib/apt/lists/*
        
        # Install Poetry
        RUN curl -sSL https://install.python-poetry.org | python3 -
        ENV PATH="/root/.local/bin:$PATH"
        
        WORKDIR /app
        COPY . .
        
        # Install dependencies
        RUN poetry config virtualenvs.create false && \
            poetry install --no-interaction --no-ansi --no-root && \
            pip install pyinstaller
        
        # Build a Linux binary that can work on macOS with Rosetta (Intel)
        # Note: This is not a true macOS binary but may work with compatibility layers
        RUN pyinstaller openhands-cli.spec --clean --noconfirm
        
        # Package with a note
        RUN echo "This binary was cross-compiled from Linux. For best compatibility, build on native macOS." > dist/macos-note.txt && \
            cd dist && \
            tar -czf openhands-darwin-x86_64.tar.gz openhands macos-note.txt
        
        VOLUME ["/output"]
        CMD ["sh", "-c", "cp /app/dist/*.tar.gz /output/"]
        EOF
    
    - name: Build macOS-compatible binary
      run: |
        docker build -f Dockerfile.macos-cross -t openhands-macos-builder .
        mkdir -p dist-macos
        docker run --rm -v "$(pwd)/dist-macos:/output" openhands-macos-builder
        ls -la dist-macos/
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: openhands-darwin-x86_64
        path: dist-macos/*

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Generate release tag
      id: generate_tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          if [[ "${{ github.event.inputs.version }}" == "manual" ]]; then
            TAG="docker-all-$(date +'%Y%m%d-%H%M%S')"
          else
            TAG="${{ github.event.inputs.version }}"
          fi
        else
          TAG="${{ github.ref_name }}"
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.generate_tag.outputs.tag }}
        release_name: OpenHands CLI ${{ steps.generate_tag.outputs.tag }} (Docker Cross-Platform Build)
        body: |
          ## OpenHands CLI Binary Release (Docker Cross-Platform Build)
          
          This release includes:
          - **Linux** (x86_64) - Native build in Docker ✅
          - **Windows** (x86_64) - Build instructions (cross-compilation not supported) 📄
          - **macOS** (x86_64) - Linux binary (may work with compatibility layers) ⚠️
          
          ### ⚠️ Important Notes
          
          - **Windows**: True Windows cross-compilation in Docker is not practical. See the included instructions for building on Windows.
          - **macOS**: The provided binary is Linux-based. It may work on Intel Macs with Rosetta 2 or Docker Desktop. For native macOS binary, build on actual macOS hardware.
          
          ### Installation
          
          1. Download the appropriate binary for your platform
          2. Extract the archive
          3. Make the binary executable (Unix systems): `chmod +x openhands*`
          4. Move to your PATH or run directly
          
          ### Usage
          
          ```bash
          openhands --help
          ```
          
          ### For Production Use
          
          For production deployments, we recommend using the native build workflow (`build-cli-binaries.yml`) which builds on actual OS runners for better compatibility.
        draft: false
        prerelease: false

    - name: Upload Release Assets
      run: |
        for file in artifacts/*/*; do
          if [[ -f "$file" ]]; then
            echo "Uploading $file"
            gh release upload "${{ steps.generate_tag.outputs.tag }}" "$file" --clobber
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}