name: Build CLI Binaries (Test)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-cli-binaries-test.yml'
      - 'openhands-cli.spec'
      - 'openhands/cli/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install minimal dependencies
      run: |
        # Install dependencies using existing pyproject.toml
        poetry install --no-interaction --no-ansi
        
        # Install PyInstaller explicitly
        poetry run pip install pyinstaller
        
        # Debug: Check if pyinstaller is installed
        poetry run pip list | grep -i pyinstaller || echo "PyInstaller not found in pip list"
        poetry run which pyinstaller || echo "PyInstaller binary not found"
    
    - name: Test PyInstaller build
      run: |
        # Build using the spec file
        poetry run pyinstaller openhands-cli.spec --clean --noconfirm
        
        # Check if binary was created
        ls -la dist/
        
        # Test the binary
        ./dist/openhands --version || echo "Binary test failed"
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-binary-linux
        path: dist/openhands